spring:
  datasource:
    url: jdbc:postgresql://172.17.0.1:5432/postgres
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate:
        default_schema: prod
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
